server:
  port: 9000

spring:
  application:
    name: EXPENSE-REIMBURSEMENT
  datasource:
    url: jdbc:mysql://localhost:3306/expensedb
    username: root
    password: Ajul03330@
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
